### ISSUE TITLE
Header only resized after did appear

### ISSUE THREAD

**Issue by steven851007** [roadfire/AutoLayoutTableHeaderView#1]
Add a new view controller to the storyboard and push the tableview from there:
- The tableview's header only resized when the view controller is already visible, which gives a really bad user experience

**Comment by joshuatbrown** [comment]
Thanks! Do you have a sample project that shows the problem? I'd really appreciate a pull request, but even if you just have a sample project I'd appreciate it.

**Comment by allaire** [comment]
@joshuatbrown @steven851007 This is also working in `viewDidLoad`. Can you advice what's the best place to put it?

Also, why did you drag a TableView in a VC instead of directly using a Table View Controller?

Thanks!

**Comment by joshuatbrown** [comment]
@allaire I'd probably put it in `viewDidLayoutSubviews` rather than `viewDidLoad`. Don't quote me on this, but I _think_ `viewDidLayoutSubviews` gets called when you rotate from portrait to landscape or vice versa, so it's probably a better place to handle this.

Regarding your other question - I almost always drop a table view on a VC instead of using a Table View Controller because the regular VC approach provides much more flexibility. With a Table View Controller, your table view has to take up the entire screen, and often I don't want that.

**Comment by allaire** [comment]
@joshuatbrown thanks for the update.

Right for the VC / TableView part. What I started to do is using a VC with a container view and another Tableview controller, so I can nest it in another place!

**Comment by idevsoftware** [comment]
Thank you for your post and implementation. Not to reopen the issue, but IMHO the resizing should happen in `viewWillLayoutSubviews` to avoid the header view from 'jumping' in place. Also, it should be enclosed in a `dispatch_once` block/enclosure to avoid it from being called on every point of the tableView scrolling.

**Comment by joshuatbrown** [comment]
@idevsoftware Thanks for the suggestion. I'd be happy to see how that works; create a PR and I'll take a look!

**Comment by frankus** [comment]
Doing this in `-viewDid/WillLayoutSubviews` seems to cause an infinite loop (I'm guessing setting the header view kicks off another layout pass). And using `dispatch_once` in an instance method is problematic (for example, if the controller is dismissed and presented again, the code in the block won't execute a second time). 

There doesn't seem to be a really ideal place for it, but experimentally inside `-updateViewContraints` works for me. 

_UPDATE_: Doesn't work on a real device.

**Comment by frankus** [comment]
Finally figured out the "right" place to do this in iOS 8 and later: 

```
- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
        self.tableView.tableHeaderView = self.myTableHeaderView;
    } completion:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
    }];
}
```
