### ISSUE TITLE
Infinitely calling viewDidLayoutSubviews

### ISSUE THREAD

**Issue by danielgalasko** [roadfire/AutoLayoutTableHeaderView#3]
Firstly I loved the tutorial. Really great. Only addition I want to contribute to prevent the view from being laid out indefinitely:

``` swift
    if frame.size.height != size.height {
        frame.size.height = size.height
        headerView.frame = frame
        tableView.tableHeaderView = headerView
    }
```

**Comment by joshuatbrown** [comment]
Thank you! Is there a way to do this without checking the frame height? Seems like there should be a way...

**Comment by danielgalasko** [comment]
I guess you could do a `CGSizeEqualToSize`, that will probably cover rotation and other possibilities. But yeah, just opened this when I noticed some nasty recursion going on in iOS 8.4 by setting the header after layout

**Comment by joshuatbrown** [comment]
Yep, definitely a problem that needs to be solved - thanks for bringing this up! Maybe it needs to be done somewhere besides `viewDidLayoutSubviews`? I'll investigate.

**Comment by danielgalasko** [comment]
Unless you have a custom `UITableView` that can adequately manage the layout cycle I don't see a better choice really. Technically this should end up as a radar as this is unnecessary dancing around the implementation to get desired behaviour.

**Comment by joshuatbrown** [comment]
Finally got around to testing this - I'm not seeing any recursion in iOS 8.4. Can you explain the steps you took to make cause the recursion to happen? And where did you notice it?

**Comment by danielgalasko** [comment]
@joshuatbrown right so I just checked out the repo and you are correct. For a typical UIViewController subclass your implementation works perfectly. However, if you change over to a UITableViewController subclass then it recurses infinitely. Would you like me to make a fork and show you?

**Comment by joshuatbrown** [comment]
@danielgalasko If you'd like to, I'd be happy to take a look. I'm going to leave this code as is for now since it seems to work for typical UIViewController subclasses - we can point people toward your fork for UITableViewController subclasses.

**Comment by FWEugene** [comment]
override  updateViewConstraints() instead of viewDidLayoutSubviews () solve the problem. 
viewDidLayoutSubviews ( ) invoked every time you change frame of the subview ( the header is one of the subviews of tableView). This give's use internal loop.
This is true if you use UITableViewController. If you use UIViewController and then add tableView as subview to view this works fine.

**Comment by joshuatbrown** [comment]
@FWEugene thanks!
